<?php
/**
 * ||GEISSWEB| Electronic Invoicing Attributes
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2025 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

declare(strict_types=1);

namespace Geissweb\ElectronicInvoicingAttributes\Api\Data;

/**
 * Interface for electronic invoicing quote extension data
 */
interface QuoteEInvoicingInterface
{
    public const ENTITY_ID = 'entity_id';
    public const QUOTE_ID = 'quote_id';
    public const BUYER_REFERENCE = 'buyer_reference';
    public const PROJECT_REFERENCE = 'project_reference';

    /**
     * Get entity ID
     *
     * @return int|null
     */
    public function getEntityId(): ?int;

    /**
     * Set entity ID
     *
     * @param int $entityId
     * @return self
     */
    public function setEntityId(int $entityId): self;

    /**
     * Get quote ID
     *
     * @return int|null
     */
    public function getQuoteId(): ?int;

    /**
     * Set quote ID
     *
     * @param int $quoteId
     * @return self
     */
    public function setQuoteId(int $quoteId): self;

    /**
     * Get buyer reference (BT-10)
     *
     * @return string|null
     */
    public function getBuyerReference(): ?string;

    /**
     * Set buyer reference (BT-10)
     *
     * @param string|null $buyerReference
     * @return self
     */
    public function setBuyerReference(?string $buyerReference): self;

    /**
     * Get project reference (BT-11)
     *
     * @return string|null
     */
    public function getProjectReference(): ?string;

    /**
     * Set project reference (BT-11)
     *
     * @param string|null $projectReference
     * @return self
     */
    public function setProjectReference(?string $projectReference): self;
}
